input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [type] == "nodejs" {
    mutate {
      add_field => { "[@metadata][index_name]" => "tfxhub-nodejs-%{+YYYY.MM.dd}" }
    }
  }
  if [type] == "dotnet" {
    mutate {
      add_field => { "[@metadata][index_name]" => "tfxhub-dotnet-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  file {
    path => "/usr/share/logstash/logs/tfxhub-%{+YYYY-MM-dd}.log"
    codec => json
    create_if_deleted => true
  }
  stdout {
    codec => rubydebug
  }
}
